[package]
name = "simpledb"
version = "0.1.0"
edition = "2021"
authors = ["Sho Kuroda <krdlab@gmail.com>"]
license = "MIT"

[dependencies]
byte = "0.2"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3"
